# Generated by Django 5.2.17 on 2026-09-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_masa', models.CharField(choices=[('Masa delgada', 'Masa delgada'), ('Masa tradicional', 'Masa tradicional'), ('Masa integral', 'Masa integral'), ('Masa artesanal', 'Masa artesanal')], max_length=50)),
                ('ingredientes', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
    ]
