# Generated by Django 5.2.17 on 2026-09-12 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_metodopago_descripcion_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('delivery', 'Delivery')], default='presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pizzeria.repartidor'),
        ),
    ]
