# Generated by Django 5.2.17 on 2026-09-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_alter_repartidor_options_repartidor_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('gr', 'Gramos (gr)'), ('ml', 'Mililitros (ml)'), ('un', 'Unidades (un)'), ('kg', 'Kilogramos (kg)'), ('lt', 'Litros (lt)')], default='gr', max_length=20),
        ),
    ]
