# Generated by Django 5.2.17 on 2026-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_pedido_tipo_pedido_alter_pedido_repartidor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repartidor',
            options={},
        ),
        migrations.AddField(
            model_name='repartidor',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
